# Generated by Django 4.1.5 on 2023-02-16 16:17

import autoslug.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import embed_video.fields
import fiches.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("resume", models.TextField(blank=True)),
                ("content", models.TextField(blank=True)),
                (
                    "date_pub",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Publication date"
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from=models.CharField(max_length=250)
                    ),
                ),
                ("publish", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "article",
                "verbose_name_plural": "articles",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("firstname", models.CharField(blank=True, max_length=250)),
                ("group", models.BooleanField(default=False)),
                ("bio", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from=models.CharField(max_length=250)
                    ),
                ),
                (
                    "pronoun",
                    models.CharField(
                        blank=True,
                        choices=[("Her", "Her"), ("They", "They/Them"), ("Him", "Him")],
                        default="Her",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "author",
                "verbose_name_plural": "authors",
                "ordering": ("name", "group"),
            },
        ),
        migrations.CreateModel(
            name="Licence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("open", models.BooleanField(default=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from=models.CharField(max_length=250)
                    ),
                ),
            ],
            options={
                "verbose_name": "licence",
                "verbose_name_plural": "licences",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Notion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("content", models.TextField(blank=True)),
                ("publish", models.BooleanField(default=False)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from=models.CharField(max_length=250)
                    ),
                ),
            ],
            options={
                "verbose_name": "notion",
                "verbose_name_plural": "notions",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, null=True)),
                (
                    "date_pub",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Publication date"
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        blank=True,
                        default=datetime.datetime(2000, 1, 1, 0, 0),
                        null=True,
                        verbose_name="Creation date",
                    ),
                ),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from=models.CharField(max_length=250)
                    ),
                ),
                ("video", embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ("publish", models.BooleanField(default=False)),
                (
                    "temporality",
                    models.CharField(
                        blank=True,
                        choices=[("Event", "Event"), ("Continuous", "Continuous")],
                        default="Event",
                        max_length=15,
                    ),
                ),
                (
                    "usage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Collaboration", "Collaboration"),
                            ("Cooperation", "Cooperation"),
                            ("Contribution", "Contribution"),
                            ("Participatory", "Participatory"),
                        ],
                        default="Collaboration",
                        max_length=15,
                    ),
                ),
                (
                    "environnement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Web", "Web"),
                            ("Desktop", "Desktop"),
                            ("Mobile", "Mobile"),
                        ],
                        default="Web",
                        max_length=10,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.author",
                    ),
                ),
                (
                    "licence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fiches.licence",
                    ),
                ),
                ("notion", models.ManyToManyField(blank=True, to="fiches.notion")),
            ],
            options={
                "verbose_name": "project",
                "verbose_name_plural": "projects",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="ImageProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legende", models.CharField(max_length=200)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=0.5,
                        size=[1920, 1080],
                        upload_to=fiches.models.get_img,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fiches.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legende", models.CharField(max_length=200)),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=0.5,
                        size=[1920, 1080],
                        upload_to=fiches.models.get_img,
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fiches.article",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fiches.author",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="licence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="fiches.licence",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="notion",
            field=models.ManyToManyField(blank=True, to="fiches.notion"),
        ),
    ]
