# Generated by Django 4.1.5 on 2023-02-16 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="licence",
            options={
                "ordering": ("title",),
                "verbose_name": "licence",
                "verbose_name_plural": "licences",
            },
        ),
        migrations.RenameField(
            model_name="licence",
            old_name="name",
            new_name="title",
        ),
    ]
