# Generated by Django 4.1.5 on 2023-02-20 09:41

from django.db import migrations, models
import django_resized.forms
import fiches.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fiches",
            "0003_article_md_file_alter_article_slug_alter_author_slug_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="no_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="md_file",
            field=models.FileField(blank=True, null=True, upload_to="article"),
        ),
        migrations.AlterField(
            model_name="imagearticle",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=1,
                size=[1920, 1080],
                upload_to=fiches.models.get_article_image_filename,
            ),
        ),
        migrations.AlterField(
            model_name="imageproject",
            name="image",
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=1,
                size=[1920, 1080],
                upload_to=fiches.models.get_img,
            ),
        ),
    ]
