# Generated by Django 4.1.5 on 2023-03-22 09:21

import autoslug.fields
from django.db import migrations
import django_resized.forms
import fiches.models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0004_project_no_date_alter_article_md_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                default="image",
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=1,
                size=[1580, 1000],
                upload_to=fiches.models.get_img,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=autoslug.fields.AutoSlugField(editable=True, populate_from="name"),
        ),
    ]
