# Generated by Django 4.1.5 on 2023-03-22 09:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0005_project_thumbnail_alter_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="thumbnail",
            field=django_resized.forms.ResizedImageField(
                crop=["middle", "center"],
                force_format="WEBP",
                keep_meta=True,
                quality=100,
                scale=1,
                size=[1580, 1000],
                upload_to="thumb",
            ),
        ),
    ]
