# Generated by Django 4.1.5 on 2023-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0006_alter_project_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="environnement",
        ),
        migrations.AddField(
            model_name="project",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[("web", "Web"), ("desktop", "Desktop"), ("mobile", "Mobile")],
                default="web",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="temporality",
            field=models.CharField(
                blank=True,
                choices=[("event", "Event"), ("continuous", "Continuous")],
                default="Event",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="usage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("collaboration", "Collaboration"),
                    ("cooperation", "Cooperation"),
                    ("contribution", "Contribution"),
                    ("participatory", "Participatory"),
                ],
                default="Collaboration",
                max_length=15,
            ),
        ),
    ]
