# Generated by Django 4.1.5 on 2023-03-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0007_remove_project_environnement_project_environment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[("web", "Web"), ("desktop", "Desktop"), ("mobile", "Mobile")],
                default="web",
                max_length=15,
            ),
        ),
    ]
