# Generated by Django 4.1.5 on 2023-03-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0008_alter_project_environment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="temporality",
            field=models.CharField(
                blank=True,
                choices=[("event", "Event"), ("continuous", "Continuous")],
                default="event",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="usage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("collaboration", "Collaboration"),
                    ("cooperation", "Cooperation"),
                    ("contribution", "Contribution"),
                    ("participatory", "Participatory"),
                ],
                default="collaboration",
                max_length=15,
            ),
        ),
    ]
