# Generated by Django 4.1.5 on 2023-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0011_alter_article_notion_alter_article_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="reference",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
