# Generated by Django 4.1.5 on 2023-04-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0012_reference_publish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="sub_title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
