# Generated by Django 4.1.5 on 2023-04-17 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0013_alter_reference_sub_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reference",
            name="date_pub",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 0, 0),
                verbose_name="Publication date",
            ),
        ),
    ]
