# Generated by Django 4.1.5 on 2023-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0014_alter_reference_date_pub"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="publish",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notion",
            name="publish",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="pages",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="reference",
            name="publish",
            field=models.BooleanField(default=True),
        ),
    ]
