# Generated by Django 4.1.5 on 2023-04-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0015_author_publish_alter_notion_publish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="usage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("collaboration", "Collaboration"),
                    ("contribution", "Contribution"),
                    ("participation", "Participation"),
                ],
                default="collaboration",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="reference",
            name="editor",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
