# Generated by Django 4.1.5 on 2023-04-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0016_alter_project_usage_alter_reference_editor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="md_file",
        ),
        migrations.AlterField(
            model_name="project",
            name="environment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("web", "Web"),
                    ("desktop", "Desktop"),
                    ("mobile", "Mobile"),
                    ("scripting", "Scripting"),
                    ("cli", "Commande Line"),
                ],
                default="web",
                max_length=15,
            ),
        ),
    ]
