# Generated by Django 4.1.5 on 2023-04-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0017_remove_article_md_file_alter_project_environment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imagearticle",
            old_name="legende",
            new_name="legend",
        ),
        migrations.RenameField(
            model_name="imageproject",
            old_name="legende",
            new_name="legend",
        ),
        migrations.AddField(
            model_name="article",
            name="original_content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="notion",
            field=models.ManyToManyField(blank=True, to="fiches.notion"),
        ),
        migrations.RemoveField(
            model_name="article",
            name="author",
        ),
        migrations.RemoveField(
            model_name="project",
            name="author",
        ),
        migrations.AddField(
            model_name="article",
            name="author",
            field=models.ManyToManyField(blank=True, to="fiches.author"),
        ),
        migrations.AddField(
            model_name="project",
            name="author",
            field=models.ManyToManyField(blank=True, to="fiches.author"),
        ),
    ]
