# Generated by Django 4.1.5 on 2023-05-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fiches", "0019_project_short_description_alter_article_publish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="short_description",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
